### ISSUE TITLE
输入“你好”报错

### ISSUE THREAD

**Issue by Tony2h** [howl-anderson/WeatherBot#1]
链接到自己的训练好的模型上，可以启动 webchat 。
然后输入“你好”，会返回两遍下面这个错误
message handler error
Traceback (most recent call last):
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/home/tonyzh/.conda/envs/spring/lib/python3.6/site-packages/rasa_addons/webchat/__init__.py", line 126, in handle_message
    output_channel.custom_data = message['customData']
TypeError: string indices must be integers

**Comment by howl-anderson** [comment]
这个是前端和后端数据结构定义不一致导致的问题，我已经在准备发布 WeatherBot 2.0，预览地址在 https://github.com/howl-anderson/WeatherBot/tree/feature/new_version , 里面的代码更加清晰，和官方库保持一致，欢迎使用

**Comment by howl-anderson** [comment]
@Tony2h 仓库已经成最新版本
